version: '3.4'
volumes:
  node_modules:
  user_api_db:
networks:
  default:
    external:
      name: user_network
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - user_api_db:/var/lib/mysql
    ports:
      - 35001:3306
    environment:
      - MYSQL_DATABASE=user_db
      - MYSQL_ROOT_PASSWORD=root
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - 35000:35000
