version: "3.4"
volumes:
  node_modules:
services:
  user-api-node:
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - 35000:35000
